### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [igor-suhorukov/openstreetmap_h3#1]
Hello!

I found this project from https://habr.com/ru/post/714326/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by igor-suhorukov** [comment]
Hi @vazhnov 
Well spotted, thank you! Please give star for this project if you like or use it 
Fixed by last commit

**Comment by vazhnov** [comment]
Apache-2.0 license — amazing!
@igor-suhorukov, thank you!
