### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by christophlingg** [igor-suhorukov/openstreetmap_h3#3]
Hi Igor,

I stumbled upon this project and I found it very exciting and wanted to give it a try. However I have a hard time getting to run the command. I understand the Java application starts some system processes to make use of existing tools, namely osmium.

This is when I get this error:

```bash
java -jar target/osm-to-pgsnapshot-schema-ng-1.0-SNAPSHOT.jar -source_pbf /Users/christoph/dev/osm/andorra-latest.osm.pbf
0
6  time 2392
diff between total and processing 3251
total thread time 8511
total processing time 5260
total save time 178
total waiting for save time 2382
thread max time 2122
processing max time 1734
nodes 11274
ways 18960
relations 495
relation members 33249
multipolygon count 269
0	[-32768,32695)	7674376	65463
1 7 7.674376

docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

```

I am using MacOS 13.4 (22F66), Rancher Desktop 1.8.1, `/etc/paths` contains the directory with the docker command. Actually, when I run `docker run -w /wkd -v /Users/christoph/dev…` in bash myself the commands completes successfully. 

I assume this is not specifically related to this project as it is about making system calls from Java. Maybe you still have an idea to help me and others that bump into the same problem.

Thanks

**Comment by igor-suhorukov** [comment]
Hello @christophlingg 
I don't have MacOS to check this issue and fix it. As workaround you can use openstreetmap_h3 in Linux virtual machine inside your existing OS: Parallels, VitrualBox etc

This issue may be related to java process permission on docker socket on MacOS or with installed[docker version](https://github.com/docker/for-mac/issues/6531)

**Comment by RobvalZ** [comment]
Hi,Igor
Need a help from you.
I tried to build postgis_docker using the docker
in windows and linux,but the same error.

14.12 2024-01-06 10:32:01 (1.42 MB/s) - ‘libduckdb-linux-amd64.zip’ saved [14304509/14304509]
14.12
14.17 Archive:  libduckdb-linux-amd64.zip
14.17   inflating: ./libduckdb.so
15.23 replace ./duckdb.hpp? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
15.23 (EOF or read error, treating as "[N]one" ...)
------
Dockerfile:34
--------------------
  32 |     RUN apt-get install -y wget unzip
  33 |     RUN cd /home && git clone https://github.com/alitrack/duckdb_fdw
  34 | >>> RUN cd /home/duckdb_fdw && wget -c https://github.com/duckdb/duckdb/releases/download/v0.8.1/libduckdb-linux-amd64.zip && unzip -d . libduckdb-linux-amd64.zip && cp libduckdb.so $(/usr/lib/postgresql/15/bin/pg_config --libdir)
  35 |     RUN cd /home/duckdb_fdw &&  make PG_CONFIG=/usr/lib/postgresql/15/bin/pg_config USE_PGXS=1 && make PG_CONFIG=/usr/lib/postgresql/15/bin/pg_config install USE_PGXS=1
  36 |     RUN apt-get purge -y --auto-remove wget unzip
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /home/duckdb_fdw && wget 
-c https://github.com/duckdb/duckdb/releases/download/v0.8.1/libduckdb-linux-amd64.zip && unzip -d . libduckdb-linux-amd64.zip && cp libduckdb.so $(/usr/lib/postgresql/15/bin/pg_config --libdir)" did not complete successfully: exit code: 1

**Comment by igor-suhorukov** [comment]
> Hi,Igor Need a help from you. I tried to build postgis_docker using the docker in windows and linux,but the same error.
Hello.

@RobvalZ as temporary workaround try remove [lines 32-36](https://github.com/igor-suhorukov/openstreetmap_h3/blob/2e6d3669a98277304a07444813ee4ae7e884815d/postgis_docker-master/Dockerfile#L32) from postgis_docker-master/Dockerfile and rebuild image

**Comment by RobvalZ** [comment]
Re: [igor-suhorukov/openstreetmap_h3] Cannot connect to the Docker daemon (Issue #3)












Hi,Igor Need a help from you. I tried to build postgis_docker using the docker in windows and linux,but the same error.
Hello.


@RobvalZ as temporary workaround try remove lines 32-36 from postgis_docker-master/Dockerfile and rebuild image
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>




Many thanks for your openstreetmap_h3 project.
Everything worked out well.I've done everything
in linux,dumped and moved to Windows to worked
with DBeaver.And again Thanks.





                      ***@***.***

**Comment by igor-suhorukov** [comment]
install latest osmium version local and invoke `-osmium_docker false` or use [docker image](https://github.com/igor-suhorukov/openstreetmap_h3/blob/master/Dockerfile) with embedded osmium tools
